const TYPES={signal:1,propertyUpdate:2,init:3,idle:4,debug:5,invokeMethod:6,connectToSignal:7,disconnectFromSignal:8,setProperty:9,response:10};
export class QWebChannel{
  constructor(transport,initCallback){
    if(!transport||typeof transport.send!=="function")throw new TypeError("QWebChannel transport must provide send().");
    this.transport=transport;this.objects={};this.execCallbacks=new Map();this.execId=1;
    transport.onmessage=(message)=>{try{let data=message?.data??message;if(Buffer.isBuffer(data))data=data.toString("utf8");if(ArrayBuffer.isView(data)&&!Buffer.isBuffer(data))data=Buffer.from(data.buffer,data.byteOffset,data.byteLength).toString("utf8");if(data instanceof ArrayBuffer)data=Buffer.from(data).toString("utf8");if(typeof data==="string")data=JSON.parse(data);if(data.type===TYPES.signal)this.#handleSignal(data);else if(data.type===TYPES.response)this.#handleResponse(data);else if(data.type===TYPES.propertyUpdate)this.#handlePropertyUpdate(data);}catch{try{transport.close();}catch{}}};
    this.exec({type:TYPES.init},data=>{for(const objectName of Object.keys(data||{}))new QObject(objectName,data[objectName],this);for(const objectName of Object.keys(this.objects))this.objects[objectName].unwrapProperties();initCallback?.(this);this.exec({type:TYPES.idle});});
  }
  send(data){this.transport.send(typeof data==="string"?data:JSON.stringify(data));}
  exec(data,callback){if(!callback){this.send(data);return;}const id=this.execId++;this.execCallbacks.set(id,callback);this.send({...data,id});}
  #handleSignal(message){this.objects[message.object]?.signalEmitted(message.signal,message.args||[]);}
  #handleResponse(message){const callback=this.execCallbacks.get(message.id);if(!callback)return;this.execCallbacks.delete(message.id);callback(message.data);}
  #handlePropertyUpdate(message){for(const data of message.data||[])this.objects[data.object]?.propertyUpdate(data.signals||{},data.properties||{});this.exec({type:TYPES.idle});}
}
class QObject{
  constructor(name,data,webChannel){this.__id__=name;this.__webChannel__=webChannel;this.__objectSignals__={};this.__propertyCache__={};webChannel.objects[name]=this;for(const method of data.methods||[])this.#addMethod(method);for(const prop of data.properties||[])this.#bindProperty(prop);for(const signal of data.signals||[])this.#addSignal(signal,false);Object.assign(this,data.enums||{});}
  unwrapQObject(response){if(Array.isArray(response))return response.map(v=>this.unwrapQObject(v));if(!response||typeof response!=="object")return response;if(!response["__QObject*__"]||response.id===undefined){const out={};for(const[k,v]of Object.entries(response))out[k]=this.unwrapQObject(v);return out;}if(this.__webChannel__.objects[response.id])return this.__webChannel__.objects[response.id];if(!response.data)return undefined;const qobj=new QObject(response.id,response.data,this.__webChannel__);if(qobj.destroyed?.connect)qobj.destroyed.connect(()=>{if(this.__webChannel__.objects[response.id]===qobj)delete this.__webChannel__.objects[response.id];});qobj.unwrapProperties();return qobj;}
  unwrapProperties(){for(const key of Object.keys(this.__propertyCache__))this.__propertyCache__[key]=this.unwrapQObject(this.__propertyCache__[key]);}
  #addSignal(signalData,isPropertyNotifySignal){const signalName=signalData[0],signalIndex=signalData[1];if(this[signalName])return;this[signalName]={connect:callback=>{if(typeof callback!=="function")return;const list=this.__objectSignals__[signalIndex]||=[];list.push(callback);if(isPropertyNotifySignal||/^destroyed(?:\(|$)/.test(signalName))return;if(list.length===1)this.__webChannel__.exec({type:TYPES.connectToSignal,object:this.__id__,signal:signalIndex});},disconnect:callback=>{const list=this.__objectSignals__[signalIndex]||[];this.__objectSignals__[signalIndex]=list.filter(c=>c!==callback);if(!isPropertyNotifySignal&&this.__objectSignals__[signalIndex].length===0)this.__webChannel__.exec({type:TYPES.disconnectFromSignal,object:this.__id__,signal:signalIndex});}};}
  #invokeSignalCallbacks(signalIndex,args){for(const callback of this.__objectSignals__[signalIndex]||[]){try{callback(...(args||[]));}catch{}}}
  propertyUpdate(signals,propertyMap){for(const[propertyIndex,value]of Object.entries(propertyMap))this.__propertyCache__[propertyIndex]=this.unwrapQObject(value);for(const[signalIndex,args]of Object.entries(signals))this.#invokeSignalCallbacks(signalIndex,this.unwrapQObject(args));}
  signalEmitted(signalIndex,signalArgs){this.#invokeSignalCallbacks(signalIndex,this.unwrapQObject(signalArgs));}
  #addMethod(methodData){const methodName=methodData[0],methodIndex=methodData[1],invokedMethod=methodName.endsWith(")")?methodIndex:methodName;this[methodName]=(...rawArgs)=>{const args=rawArgs.filter(v=>typeof v!=="function"),providedCallback=rawArgs.find(v=>typeof v==="function");if(providedCallback){this.__webChannel__.exec({type:TYPES.invokeMethod,object:this.__id__,method:invokedMethod,args},response=>providedCallback(this.unwrapQObject(response)));return;}return new Promise(resolve=>this.__webChannel__.exec({type:TYPES.invokeMethod,object:this.__id__,method:invokedMethod,args},response=>resolve(this.unwrapQObject(response))));};}
  #bindProperty(propertyInfo){const propertyIndex=propertyInfo[0],propertyName=propertyInfo[1],notifySignalData=propertyInfo[2];this.__propertyCache__[propertyIndex]=propertyInfo[3];if(notifySignalData){const signalData=[...notifySignalData];if(signalData[0]===1)signalData[0]=`${propertyName}Changed`;this.#addSignal(signalData,true);}Object.defineProperty(this,propertyName,{configurable:true,get:()=>this.__propertyCache__[propertyIndex],set:value=>{if(value===undefined)return;this.__propertyCache__[propertyIndex]=value;this.__webChannel__.exec({type:TYPES.setProperty,object:this.__id__,property:propertyIndex,value});}});}
  toJSON(){return{id:this.__id__,"__QObject*__":true};}
}
